### ISSUE TITLE
Event sounds

### ISSUE THREAD

**Issue by stie** [mrzapp/stop-playing#17]
Question: Can pick-up sound and "win music" easily be implemented?

**Comment by mrzapp** [comment]
Win music is easy enough. Just go to the "EndGame" level and go to Blueprint > Open level blueprint and add a "Play Sound 2D" node connecting to "On Begin Play"

**Comment by mrzapp** [comment]
For grab/release sounds, go to the BP_DefaultPlayer blueprint and open the macro "PlayGrabSound" and "PlayReleaseSound". In there you can pick the assets you want to use.
